import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';

export async function POST(request: NextRequest) {
  try {
    const { title, category, address, rating, reviewCount, venueType } = await request.json();

    if (!title) {
      return NextResponse.json({
        success: false,
        error: 'Title is required'
      }, { status: 400 });
    }

    // Check if OpenAI API key is available
    if (!process.env.OPENAI_API_KEY) {
      console.log('⚠️ OpenAI API key not configured');
      return NextResponse.json({
        success: false,
        error: 'OpenAI API key not configured. Please add OPENAI_API_KEY to your environment variables.',
        code: 'MISSING_API_KEY'
      }, { status: 400 });
    }

    // Initialize OpenAI client only after checking API key
    const openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });

    console.log(`🤖 GPT Enhancement: Creating premium description for "${title}"`);

    const prompt = `You are a luxury travel writer creating premium content for Istanbul Explorer, a high-end travel platform. 

Create an engaging, informative description for this ${category} in Istanbul:

**Venue Details:**
- Name: ${title}
- Category: ${category}
- Address: ${address || 'Istanbul, Turkey'}
- Rating: ${rating || 'Not specified'}
- Review Count: ${reviewCount || 'Not specified'}
- Type: ${venueType || category}

**Requirements:**
1. Write 2-3 paragraphs (150-200 words total)
2. Capture the essence and unique appeal of this place
3. Include historical/cultural significance if relevant
4. Mention what makes it special for visitors
5. Use elegant, engaging language suitable for luxury travel
6. Avoid generic phrases like "must-visit" or "amazing"
7. Be specific about what visitors can expect
8. Include practical context (location, atmosphere, etc.)

**Tone:** Sophisticated, informative, and inspiring - like Conde Nast Traveler or National Geographic Traveler.

**Format:** Return only the description text, no additional formatting or quotes.`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: "You are an expert luxury travel writer specializing in Istanbul and Turkish culture."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      max_tokens: 300,
      temperature: 0.7,
    });

    const enhancedDescription = completion.choices[0]?.message?.content?.trim();

    if (!enhancedDescription) {
      throw new Error('No content generated by GPT');
    }

    console.log(`✅ GPT Enhancement: Generated ${enhancedDescription.length} characters for "${title}"`);

    return NextResponse.json({
      success: true,
      data: {
        enhanced_description: enhancedDescription,
        source: 'gpt-4',
        word_count: enhancedDescription.split(' ').length
      }
    });

  } catch (error) {
    console.error('❌ GPT Enhancement Error:', error);
    return NextResponse.json({
      success: false,
      error: 'Failed to enhance description',
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 });
  }
}
